//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SolarManager.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FlashPortalDBEntities : DbContext
    {
        public FlashPortalDBEntities()
            : base("name=FlashPortalDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<SubUser> SubUsers { get; set; }
        public virtual DbSet<SubUserTransaction> SubUserTransactions { get; set; }
        public virtual DbSet<SuperUserEndOfShift> SuperUserEndOfShifts { get; set; }
    }
}
