//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SolarManager.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SubUser
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SubUser()
        {
            this.SubUserTransactions = new HashSet<SubUserTransaction>();
            this.SuperUserEndOfShifts = new HashSet<SuperUserEndOfShift>();
        }
    
        public int SubUserID { get; set; }
        public string SubUserName { get; set; }
        public string SubUserPin { get; set; }
        public string UserID { get; set; }
        public bool Admin { get; set; }
        public Nullable<bool> Status { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SubUserTransaction> SubUserTransactions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SuperUserEndOfShift> SuperUserEndOfShifts { get; set; }
    }
}
