//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SolarManager.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SuperUserEndOfShift
    {
        public long id { get; set; }
        public string superUserId { get; set; }
        public Nullable<int> EOSPrintNumber { get; set; }
        public Nullable<System.DateTime> lastEOSDate { get; set; }
        public Nullable<int> subUserID { get; set; }
        public string EOSPrint { get; set; }
    
        public virtual SubUser SubUser { get; set; }
    }
}
